### ISSUE TITLE
Koala chart does not render properly in horizontal orientation

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#184] opened 2017-08-08 00:41 UTC
I haven't observed this problem with any other charts, so perhaps it is a scale issue? This is definitely not high priority, but it wouldn't hurt to understand the reason so we can better characterize the limitations of the system.

**Comment by aaronpmishkin** [comment] 2017-08-16 16:13
I'm not sure what the issue is with the Koala Chart. I will investigate.

**Comment by aaronpmishkin** [comment] 2017-08-16 21:32
I determined the cause of this issue to be the scaling of the user bar heights. The bar heights are negligible (in the horizontal orientation) when there are a large number of users and alternatives because there is simply no room in which to render them. Scaling the size of the window fixes this problem. 

I think that it is reasonable to characterize this as a "limitation of the system" for now and am going to close this issue.

**Closed by aaronpmishkin** 2017-08-16 21:32 UTC
Labels: IMPORTANCE: Low
